let strip = neopixel.create(DigitalPin.P16, 4, NeoPixelMode.RGB)
strip.clear()
strip.show()
basic.showIcon(IconNames.Yes)
basic.forever(function () {
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    strip.clear()
    basic.pause(1000)
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    strip.clear()
    basic.pause(1000)
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    strip.clear()
    basic.pause(1000)
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.White))
    strip.show()
    strip.clear()
    basic.pause(1000)
    basic.showIcon(IconNames.Happy)
})
